services:
  web:
    build:
      context: ./app
    ports:
    - '8000:8000'
    restart: 'on-failure'
    # mapping app on container
    volumes:
      - "./app:/app"
    env_file:
      - app/env/.env
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      #volume anonimowy
      - postgres:/var/lib/postgresql/data
    env_file:
      - app/env/.env
volumes:
  #docker stworzy anonimowy volume dla postgresa
  postgres: