# Generated by Django 3.2.13 on 2022-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FU', 'fundacja'), ('OP', 'organizacja pozarządowa'), ('ZL', 'zbiórka lokalna')], default='FU', max_length=2)),
                ('categories', models.ManyToManyField(to='home.Category')),
            ],
        ),
    ]
