# Generated by Django 3.2.13 on 2022-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
